class CasinoRunner {
    public static void main(String[] args) {
        Casino casino1 = new Casino();
        casino1.casinoId = 1;
        casino1.name = "Golden Nugget";
        casino1.location = "Las Vegas";
        casino1.numberOfGames = 150;
        casino1.revenue = 120.5;
        casino1.isOpen24Hours = true;
        casino1.managerName = "John Smith";
        casino1.areaInSqFt = 50000;
        casino1.employeeCount = 300;
        casino1.specialtyGame = "Blackjack";

        Casino casino2 = new Casino();
        casino2.casinoId = 2;
        casino2.name = "Bellagio";
        casino2.location = "Las Vegas";
        casino2.numberOfGames = 200;
        casino2.revenue = 250.0;
        casino2.isOpen24Hours = true;
        casino2.managerName = "Emma Watson";
        casino2.areaInSqFt = 100000;
        casino2.employeeCount = 500;
        casino2.specialtyGame = "Poker";

        Casino casino3 = new Casino();
        casino3.casinoId = 3;
        casino3.name = "Marina Bay Sands";
        casino3.location = "Singapore";
        casino3.numberOfGames = 180;
        casino3.revenue = 300.3;
        casino3.isOpen24Hours = true;
        casino3.managerName = "Lee Hsien";
        casino3.areaInSqFt = 120000;
        casino3.employeeCount = 450;
        casino3.specialtyGame = "Roulette";

        Casino casino4 = new Casino();
        casino4.casinoId = 4;
        casino4.name = "Monte Carlo";
        casino4.location = "Monaco";
        casino4.numberOfGames = 100;
        casino4.revenue = 180.8;
        casino4.isOpen24Hours = false;
        casino4.managerName = "Charles Leclerc";
        casino4.areaInSqFt = 75000;
        casino4.employeeCount = 200;
        casino4.specialtyGame = "Baccarat";

        Casino casino5 = new Casino();
        casino5.casinoId = 5;
        casino5.name = "The Venetian";
        casino5.location = "Macau";
        casino5.numberOfGames = 220;
        casino5.revenue = 400.6;
        casino5.isOpen24Hours = true;
        casino5.managerName = "David Wong";
        casino5.areaInSqFt = 130000;
        casino5.employeeCount = 600;
        casino5.specialtyGame = "Sic Bo";

        Casino casino6 = new Casino();
        casino6.casinoId = 6;
        casino6.name = "Caesars Palace";
        casino6.location = "Las Vegas";
        casino6.numberOfGames = 190;
        casino6.revenue = 280.1;
        casino6.isOpen24Hours = true;
        casino6.managerName = "Linda Gray";
        casino6.areaInSqFt = 95000;
        casino6.employeeCount = 420;
        casino6.specialtyGame = "Craps";

        Casino casino7 = new Casino();
        casino7.casinoId = 7;
        casino7.name = "Sun City";
        casino7.location = "South Africa";
        casino7.numberOfGames = 130;
        casino7.revenue = 150.5;
        casino7.isOpen24Hours = false;
        casino7.managerName = "Nelson Dlamini";
        casino7.areaInSqFt = 70000;
        casino7.employeeCount = 350;
        casino7.specialtyGame = "Slots";

        Casino casino8 = new Casino();
        casino8.casinoId = 8;
        casino8.name = "Crown Casino";
        casino8.location = "Melbourne";
        casino8.numberOfGames = 160;
        casino8.revenue = 220.0;
        casino8.isOpen24Hours = true;
        casino8.managerName = "Steve Irwin";
        casino8.areaInSqFt = 90000;
        casino8.employeeCount = 400;
        casino8.specialtyGame = "Keno";

        Casino casino9 = new Casino();
        casino9.casinoId = 9;
        casino9.name = "Foxwoods";
        casino9.location = "Connecticut";
        casino9.numberOfGames = 210;
        casino9.revenue = 310.4;
        casino9.isOpen24Hours = true;
        casino9.managerName = "Sarah Johnson";
        casino9.areaInSqFt = 110000;
        casino9.employeeCount = 470;
        casino9.specialtyGame = "Texas Hold'em";

        Casino casino10 = new Casino();
        casino10.casinoId = 10;
        casino10.name = "Resorts World";
        casino10.location = "Las Vegas";
        casino10.numberOfGames = 170;
        casino10.revenue = 275.9;
        casino10.isOpen24Hours = true;
        casino10.managerName = "Tom Hanks";
        casino10.areaInSqFt = 102000;
        casino10.employeeCount = 390;
        casino10.specialtyGame = "Pai Gow";

        Casino casino11 = new Casino();
        casino11.casinoId = 11;
        casino11.name = "WinStar World";
        casino11.location = "Oklahoma";
        casino11.numberOfGames = 250;
        casino11.revenue = 450.2;
        casino11.isOpen24Hours = true;
        casino11.managerName = "Mary Sue";
        casino11.areaInSqFt = 200000;
        casino11.employeeCount = 800;
        casino11.specialtyGame = "Three Card Poker";

        Casino casino12 = new Casino();
        casino12.casinoId = 12;
        casino12.name = "Galaxy Macau";
        casino12.location = "Macau";
        casino12.numberOfGames = 230;
        casino12.revenue = 360.0;
        casino12.isOpen24Hours = true;
        casino12.managerName = "Tony Chan";
        casino12.areaInSqFt = 125000;
        casino12.employeeCount = 510;
        casino12.specialtyGame = "Fan Tan";

        Casino casino13 = new Casino();
        casino13.casinoId = 13;
        casino13.name = "Atlantis Casino";
        casino13.location = "Bahamas";
        casino13.numberOfGames = 140;
        casino13.revenue = 190.3;
        casino13.isOpen24Hours = false;
        casino13.managerName = "Nancy Drew";
        casino13.areaInSqFt = 80000;
        casino13.employeeCount = 270;
        casino13.specialtyGame = "Caribbean Stud Poker";

        Casino casino14 = new Casino();
        casino14.casinoId = 14;
        casino14.name = "Hippodrome Casino";
        casino14.location = "London";
        casino14.numberOfGames = 120;
        casino14.revenue = 170.5;
        casino14.isOpen24Hours = false;
        casino14.managerName = "Arthur Doyle";
        casino14.areaInSqFt = 60000;
        casino14.employeeCount = 250;
        casino14.specialtyGame = "Pontoon";

        Casino casino15 = new Casino();
        casino15.casinoId = 15;
        casino15.name = "Casino Lisboa";
        casino15.location = "Lisbon";
        casino15.numberOfGames = 110;
        casino15.revenue = 145.0;
        casino15.isOpen24Hours = true;
        casino15.managerName = "Luis Figo";
        casino15.areaInSqFt = 68000;
        casino15.employeeCount = 300;
        casino15.specialtyGame = "Rummy";

        Casino casino16 = new Casino();
        casino16.casinoId = 16;
        casino16.name = "Treasure Island";
        casino16.location = "Las Vegas";
        casino16.numberOfGames = 150;
        casino16.revenue = 210.4;
        casino16.isOpen24Hours = true;
        casino16.managerName = "Tina Fey";
        casino16.areaInSqFt = 85000;
        casino16.employeeCount = 330;
        casino16.specialtyGame = "Let It Ride";

        Casino casino17 = new Casino();
        casino17.casinoId = 17;
        casino17.name = "Harrah's";
        casino17.location = "New Orleans";
        casino17.numberOfGames = 160;
        casino17.revenue = 205.2;
        casino17.isOpen24Hours = true;
        casino17.managerName = "Steve Nash";
        casino17.areaInSqFt = 87000;
        casino17.employeeCount = 340;
        casino17.specialtyGame = "Chuck-a-luck";

        Casino casino18 = new Casino();
        casino18.casinoId = 18;
        casino18.name = "Mohegan Sun";
        casino18.location = "Connecticut";
        casino18.numberOfGames = 200;
        casino18.revenue = 325.6;
        casino18.isOpen24Hours = true;
        casino18.managerName = "Jessica Alba";
        casino18.areaInSqFt = 100000;
        casino18.employeeCount = 460;
        casino18.specialtyGame = "Big Six Wheel";

        Casino casino19 = new Casino();
        casino19.casinoId = 19;
        casino19.name = "Red Rock Casino";
        casino19.location = "Las Vegas";
        casino19.numberOfGames = 170;
        casino19.revenue = 195.7;
        casino19.isOpen24Hours = true;
        casino19.managerName = "George Clooney";
        casino19.areaInSqFt = 91000;
        casino19.employeeCount = 380;
        casino19.specialtyGame = "Crapless Craps";

        Casino casino20 = new Casino();
        casino20.casinoId = 20;
        casino20.name = "The Mirage";
        casino20.location = "Las Vegas";
        casino20.numberOfGames = 190;
        casino20.revenue = 220.8;
        casino20.isOpen24Hours = true;
        casino20.managerName = "Morgan Freeman";
        casino20.areaInSqFt = 96000;
        casino20.employeeCount = 400;
        casino20.specialtyGame = "Roulette";
		casino.getCasinoInfo();
casino1.getCasinoInfo();
casino2.getCasinoInfo();
casino3.getCasinoInfo();
casino4.getCasinoInfo();
casino5.getCasinoInfo();
casino6.getCasinoInfo();
casino7.getCasinoInfo();
casino8.getCasinoInfo();
casino9.getCasinoInfo();
casino10.getCasinoInfo();
casino11.getCasinoInfo();
casino12.getCasinoInfo();
casino13.getCasinoInfo();
casino14.getCasinoInfo();
casino15.getCasinoInfo();
casino16.getCasinoInfo();
casino17.getCasinoInfo();
casino18.getCasinoInfo();
casino19.getCasinoInfo();

    }
}
