public class CourtCaseRunner {
    public static void main(String[] args) {

        CourtCase case1 = new CourtCase();
        case1.caseId = 101;
        case1.caseType = "Civil";
        case1.plaintiff = "Ravi";
        case1.defendant = "Shyam";
        case1.courtName = "City Court A";
        case1.judgeName = "Judge Rao";
        case1.filingDate = "01-01-2025";
        case1.hearingDate = "15-01-2025";
        case1.status = "Open";
        case1.caseValue = 50000.0;
        case1.getCourtCaseInfo();

        CourtCase case2 = new CourtCase();
        case2.caseId = 102;
        case2.caseType = "Criminal";
        case2.plaintiff = "Govt";
        case2.defendant = "Arun";
        case2.courtName = "City Court B";
        case2.judgeName = "Judge Mehta";
        case2.filingDate = "03-01-2025";
        case2.hearingDate = "20-01-2025";
        case2.status = "Scheduled";
        case2.caseValue = 100000.0;
        case2.getCourtCaseInfo();

        CourtCase case3 = new CourtCase();
        case3.caseId = 103;
        case3.caseType = "Family";
        case3.plaintiff = "Neha";
        case3.defendant = "Amit";
        case3.courtName = "Family Court";
        case3.judgeName = "Judge Sharma";
        case3.filingDate = "05-01-2025";
        case3.hearingDate = "25-01-2025";
        case3.status = "Pending";
        case3.caseValue = 75000.0;
        case3.getCourtCaseInfo();

        CourtCase case4 = new CourtCase();
        case4.caseId = 104;
        case4.caseType = "Civil";
        case4.plaintiff = "Kiran";
        case4.defendant = "Rahul";
        case4.courtName = "District Court";
        case4.judgeName = "Judge Kulkarni";
        case4.filingDate = "07-01-2025";
        case4.hearingDate = "27-01-2025";
        case4.status = "Closed";
        case4.caseValue = 43000.0;
        case4.getCourtCaseInfo();

        CourtCase case5 = new CourtCase();
        case5.caseId = 105;
        case5.caseType = "Property";
        case5.plaintiff = "Sneha";
        case5.defendant = "Family";
        case5.courtName = "High Court";
        case5.judgeName = "Judge Khan";
        case5.filingDate = "08-01-2025";
        case5.hearingDate = "28-01-2025";
        case5.status = "Open";
        case5.caseValue = 120000.0;
        case5.getCourtCaseInfo();

        CourtCase case6 = new CourtCase();
        case6.caseId = 106;
        case6.caseType = "Criminal";
        case6.plaintiff = "Govt";
        case6.defendant = "Unknown";
        case6.courtName = "City Court C";
        case6.judgeName = "Judge Lal";
        case6.filingDate = "10-01-2025";
        case6.hearingDate = "30-01-2025";
        case6.status = "Scheduled";
        case6.caseValue = 90000.0;
        case6.getCourtCaseInfo();

        CourtCase case7 = new CourtCase();
        case7.caseId = 107;
        case7.caseType = "Family";
        case7.plaintiff = "Geeta";
        case7.defendant = "Mahesh";
        case7.courtName = "Family Court B";
        case7.judgeName = "Judge Patel";
        case7.filingDate = "12-01-2025";
        case7.hearingDate = "01-02-2025";
        case7.status = "Pending";
        case7.caseValue = 60000.0;
        case7.getCourtCaseInfo();

        CourtCase case8 = new CourtCase();
        case8.caseId = 108;
        case8.caseType = "Civil";
        case8.plaintiff = "Shalini";
        case8.defendant = "Anil";
        case8.courtName = "District Court B";
        case8.judgeName = "Judge Iyer";
        case8.filingDate = "13-01-2025";
        case8.hearingDate = "02-02-2025";
        case8.status = "Open";
        case8.caseValue = 81000.0;
        case8.getCourtCaseInfo();

        CourtCase case9 = new CourtCase();
        case9.caseId = 109;
        case9.caseType = "Criminal";
        case9.plaintiff = "Govt";
        case9.defendant = "Manoj";
        case9.courtName = "City Court D";
        case9.judgeName = "Judge Ramesh";
        case9.filingDate = "15-01-2025";
        case9.hearingDate = "04-02-2025";
        case9.status = "Closed";
        case9.caseValue = 65000.0;
        case9.getCourtCaseInfo();

        CourtCase case10 = new CourtCase();
        case10.caseId = 110;
        case10.caseType = "Family";
        case10.plaintiff = "Asha";
        case10.defendant = "Ravi";
        case10.courtName = "Family Court C";
        case10.judgeName = "Judge Naik";
        case10.filingDate = "16-01-2025";
        case10.hearingDate = "05-02-2025";
        case10.status = "Scheduled";
        case10.caseValue = 70000.0;
        case10.getCourtCaseInfo();
		        CourtCase case11 = new CourtCase();
        case11.caseId = 11;
        case11.caseType = "Cybercrime";
        case11.plaintiff = "TechCorp Ltd.";
        case11.defendant = "HackerX";
        case11.courtName = "Cyber Court Delhi";
        case11.judgeName = "Justice Sharma";
        case11.filingDate = "2024-01-05";
        case11.hearingDate = "2024-02-10";
        case11.status = "Pending";
        case11.caseValue = 3.2;

        CourtCase case12 = new CourtCase();
        case12.caseId = 12;
        case12.caseType = "Contract Dispute";
        case12.plaintiff = "BuildCon";
        case12.defendant = "MegaStructures";
        case12.courtName = "High Court Mumbai";
        case12.judgeName = "Justice Nair";
        case12.filingDate = "2023-09-12";
        case12.hearingDate = "2023-10-20";
        case12.status = "In Progress";
        case12.caseValue = 11.4;

        CourtCase case13 = new CourtCase();
        case13.caseId = 13;
        case13.caseType = "Fraud";
        case13.plaintiff = "Finance Corp";
        case13.defendant = "John Matrix";
        case13.courtName = "District Court Bhopal";
        case13.judgeName = "Justice Sinha";
        case13.filingDate = "2023-07-20";
        case13.hearingDate = "2023-08-05";
        case13.status = "Closed";
        case13.caseValue = 6.3;

        CourtCase case14 = new CourtCase();
        case14.caseId = 14;
        case14.caseType = "Family";
        case14.plaintiff = "Neeta";
        case14.defendant = "Kiran";
        case14.courtName = "Family Court Kochi";
        case14.judgeName = "Justice Kumar";
        case14.filingDate = "2024-04-01";
        case14.hearingDate = "2024-04-25";
        case14.status = "Pending";
        case14.caseValue = 1.1;

        CourtCase case15 = new CourtCase();
        case15.caseId = 15;
        case15.caseType = "Tax Evasion";
        case15.plaintiff = "Income Tax Dept.";
        case15.defendant = "ABC Pvt Ltd";
        case15.courtName = "Tax Court Delhi";
        case15.judgeName = "Justice Raj";
        case15.filingDate = "2022-12-10";
        case15.hearingDate = "2023-01-20";
        case15.status = "Appeal";
        case15.caseValue = 14.7;

        CourtCase case16 = new CourtCase();
        case16.caseId = 16;
        case16.caseType = "Consumer Complaint";
        case16.plaintiff = "Ramesh Kumar";
        case16.defendant = "XYZ Electronics";
        case16.courtName = "Consumer Court Patna";
        case16.judgeName = "Justice Desai";
        case16.filingDate = "2023-10-15";
        case16.hearingDate = "2023-11-10";
        case16.status = "Resolved";
        case16.caseValue = 0.6;

        CourtCase case17 = new CourtCase();
        case17.caseId = 17;
        case17.caseType = "Environmental";
        case17.plaintiff = "GreenEarth NGO";
        case17.defendant = "PolluChem Ltd.";
        case17.courtName = "Green Tribunal";
        case17.judgeName = "Justice Iyer";
        case17.filingDate = "2024-02-11";
        case17.hearingDate = "2024-03-05";
        case17.status = "In Progress";
        case17.caseValue = 8.4;

        CourtCase case18 = new CourtCase();
        case18.caseId = 18;
        case18.caseType = "Medical Negligence";
        case18.plaintiff = "Shalini Rao";
        case18.defendant = "City Hospital";
        case18.courtName = "District Court Pune";
        case18.judgeName = "Justice Verma";
        case18.filingDate = "2023-11-20";
        case18.hearingDate = "2024-01-15";
        case18.status = "Under Review";
        case18.caseValue = 5.0;

        CourtCase case19 = new CourtCase();
        case19.caseId = 19;
        case19.caseType = "Defamation";
        case19.plaintiff = "Actor Y";
        case19.defendant = "Magazine X";
        case19.courtName = "High Court Chennai";
        case19.judgeName = "Justice Raghavan";
        case19.filingDate = "2023-06-18";
        case19.hearingDate = "2023-07-10";
        case19.status = "Appeal";
        case19.caseValue = 4.3;

        CourtCase case20 = new CourtCase();
        case20.caseId = 20;
        case20.caseType = "Property Dispute";
        case20.plaintiff = "Suresh";
        case20.defendant = "Ramesh";
        case20.courtName = "District Court Mysore";
        case20.judgeName = "Justice Kiran";
        case20.filingDate = "2022-05-10";
        case20.hearingDate = "2022-06-15";
        case20.status = "Closed";
        case20.caseValue = 2.9;
case1.getCourtCaseInfo();
case2.getCourtCaseInfo();
case3.getCourtCaseInfo();
case4.getCourtCaseInfo();
case5.getCourtCaseInfo();
case6.getCourtCaseInfo();
case7.getCourtCaseInfo();
case8.getCourtCaseInfo();
case9.getCourtCaseInfo();
case10.getCourtCaseInfo();
case11.getCourtCaseInfo();
case12.getCourtCaseInfo();
case13.getCourtCaseInfo();
case14.getCourtCaseInfo();
case15.getCourtCaseInfo();
case16.getCourtCaseInfo();
case17.getCourtCaseInfo();
case18.getCourtCaseInfo();
case19.getCourtCaseInfo();
case20.getCourtCaseInfo();

       
    }
}
