public class HatMain {
    public static void main(String[] args) {

        Hat hat1 = new Hat();
        hat1.hatId = 201;
        hat1.style = "Baseball";
        hat1.color = "Red";
        hat1.material = "Cotton";
        hat1.brand = "Nike";
        hat1.price = 15.99;
        hat1.isAdjustable = true;
        System.out.println("Hat 1: ");
        System.out.println("Hat ID: " + hat1.hatId);
        System.out.println("Style: " + hat1.style);
        System.out.println("Color: " + hat1.color);
        System.out.println("Material: " + hat1.material);
        System.out.println("Brand: " + hat1.brand);
        System.out.println("Price: " + hat1.price);
        System.out.println("Is Adjustable: " + hat1.isAdjustable);
        System.out.println();

        Hat hat2 = new Hat();
        hat2.hatId = 202;
        hat2.style = "Fedora";
        hat2.color = "Black";
        hat2.material = "Wool";
        hat2.brand = "Stetson";
        hat2.price = 45.50;
        hat2.isAdjustable = false;
        System.out.println("Hat 2: ");
        System.out.println("Hat ID: " + hat2.hatId);
        System.out.println("Style: " + hat2.style);
        System.out.println("Color: " + hat2.color);
        System.out.println("Material: " + hat2.material);
        System.out.println("Brand: " + hat2.brand);
        System.out.println("Price: " + hat2.price);
        System.out.println("Is Adjustable: " + hat2.isAdjustable);
        System.out.println();

        Hat hat3 = new Hat();
        hat3.hatId = 203;
        hat3.style = "Beanie";
        hat3.color = "Gray";
        hat3.material = "Acrylic";
        hat3.brand = "Carhartt";
        hat3.price = 12.00;
        hat3.isAdjustable = false;
        System.out.println("Hat 3: ");
        System.out.println("Hat ID: " + hat3.hatId);
        System.out.println("Style: " + hat3.style);
        System.out.println("Color: " + hat3.color);
        System.out.println("Material: " + hat3.material);
        System.out.println("Brand: " + hat3.brand);
        System.out.println("Price: " + hat3.price);
        System.out.println("Is Adjustable: " + hat3.isAdjustable);
        System.out.println();

        Hat hat4 = new Hat();
        hat4.hatId = 204;
        hat4.style = "Sun Hat";
        hat4.color = "Beige";
        hat4.material = "Straw";
        hat4.brand = "Outdoor";
        hat4.price = 20.75;
        hat4.isAdjustable = true;
        System.out.println("Hat 4: ");
        System.out.println("Hat ID: " + hat4.hatId);
        System.out.println("Style: " + hat4.style);
        System.out.println("Color: " + hat4.color);
        System.out.println("Material: " + hat4.material);
        System.out.println("Brand: " + hat4.brand);
        System.out.println("Price: " + hat4.price);
        System.out.println("Is Adjustable: " + hat4.isAdjustable);
        System.out.println();

        Hat hat5 = new Hat();
        hat5.hatId = 205;
        hat5.style = "Bucket";
        hat5.color = "Blue";
        hat5.material = "Denim";
        hat5.brand = "Levi's";
        hat5.price = 18.00;
        hat5.isAdjustable = false;
        System.out.println("Hat 5: ");
        System.out.println("Hat ID: " + hat5.hatId);
        System.out.println("Style: " + hat5.style);
        System.out.println("Color: " + hat5.color);
        System.out.println("Material: " + hat5.material);
        System.out.println("Brand: " + hat5.brand);
        System.out.println("Price: " + hat5.price);
        System.out.println("Is Adjustable: " + hat5.isAdjustable);
        System.out.println();

        Hat hat6 = new Hat();
        hat6.hatId = 206;
        hat6.style = "Bowler";
        hat6.color = "Brown";
        hat6.material = "Felt";
        hat6.brand = "Classic";
        hat6.price = 35.00;
        hat6.isAdjustable = false;
        System.out.println("Hat 6: ");
        System.out.println("Hat ID: " + hat6.hatId);
        System.out.println("Style: " + hat6.style);
        System.out.println("Color: " + hat6.color);
        System.out.println("Material: " + hat6.material);
        System.out.println("Brand: " + hat6.brand);
        System.out.println("Price: " + hat6.price);
        System.out.println("Is Adjustable: " + hat6.isAdjustable);
        System.out.println();

        Hat hat7 = new Hat();
        hat7.hatId = 207;
        hat7.style = "Trilby";
        hat7.color = "Dark Gray";
        hat7.material = "Wool";
        hat7.brand = "TopHat";
        hat7.price = 40.00;
        hat7.isAdjustable = false;
        System.out.println("Hat 7: ");
        System.out.println("Hat ID: " + hat7.hatId);
        System.out.println("Style: " + hat7.style);
        System.out.println("Color: " + hat7.color);
        System.out.println("Material: " + hat7.material);
        System.out.println("Brand: " + hat7.brand);
        System.out.println("Price: " + hat7.price);
        System.out.println("Is Adjustable: " + hat7.isAdjustable);
        System.out.println();

        Hat hat8 = new Hat();
        hat8.hatId = 208;
        hat8.style = "Visor";
        hat8.color = "White";
        hat8.material = "Polyester";
        hat8.brand = "SportX";
        hat8.price = 10.50;
        hat8.isAdjustable = true;
        System.out.println("Hat 8: ");
        System.out.println("Hat ID: " + hat8.hatId);
        System.out.println("Style: " + hat8.style);
        System.out.println("Color: " + hat8.color);
        System.out.println("Material: " + hat8.material);
        System.out.println("Brand: " + hat8.brand);
        System.out.println("Price: " + hat8.price);
        System.out.println("Is Adjustable: " + hat8.isAdjustable);
        System.out.println();

        Hat hat9 = new Hat();
        hat9.hatId = 209;
        hat9.style = "Snapback";
        hat9.color = "Black";
        hat9.material = "Cotton Blend";
        hat9.brand = "UrbanWear";
        hat9.price = 22.00;
        hat9.isAdjustable = true;
        System.out.println("Hat 9: ");
        System.out.println("Hat ID: " + hat9.hatId);
        System.out.println("Style: " + hat9.style);
        System.out.println("Color: " + hat9.color);
        System.out.println("Material: " + hat9.material);
        System.out.println("Brand: " + hat9.brand);
        System.out.println("Price: " + hat9.price);
        System.out.println("Is Adjustable: " + hat9.isAdjustable);
        System.out.println();

        Hat hat10 = new Hat();
        hat10.hatId = 210;
        hat10.style = "Panama";
        hat10.color = "Tan";
        hat10.material = "Straw";
        hat10.brand = "TropicWear";
        hat10.price = 50.00;
        hat10.isAdjustable = false;
        System.out.println("Hat 10: ");
        System.out.println("Hat ID: " + hat10.hatId);
        System.out.println("Style: " + hat10.style);
        System.out.println("Color: " + hat10.color);
        System.out.println("Material: " + hat10.material);
        System.out.println("Brand: " + hat10.brand);
        System.out.println("Price: " + hat10.price);
        System.out.println("Is Adjustable: " + hat10.isAdjustable);
        System.out.println();

        Hat hat11 = new Hat();
        hat11.hatId = 211;
        hat11.style = "Beret";
        hat11.color = "Red";
        hat11.material = "Wool";
        hat11.brand = "FrenchStyle";
        hat11.price = 30.00;
        hat11.isAdjustable = false;
        System.out.println("Hat 11: ");
        System.out.println("Hat ID: " + hat11.hatId);
        System.out.println("Style: " + hat11.style);
        System.out.println("Color: " + hat11.color);
        System.out.println("Material: " + hat11.material);
        System.out.println("Brand: " + hat11.brand);
        System.out.println("Price: " + hat11.price);
        System.out.println("Is Adjustable: " + hat11.isAdjustable);
        System.out.println();

        Hat hat12 = new Hat();
        hat12.hatId = 212;
        hat12.style = "Cowboy";
        hat12.color = "Brown";
        hat12.material = "Leather";
        hat12.brand = "Western";
        hat12.price = 60.00;
        hat12.isAdjustable = true;
        System.out.println("Hat 12: ");
        System.out.println("Hat ID: " + hat12.hatId);
        System.out.println("Style: " + hat12.style);
        System.out.println("Color: " + hat12.color);
        System.out.println("Material: " + hat12.material);
        System.out.println("Brand: " + hat12.brand);
        System.out.println("Price: " + hat12.price);
        System.out.println("Is Adjustable: " + hat12.isAdjustable);
        System.out.println();

        Hat hat13 = new Hat();
        hat13.hatId = 213;
        hat13.style = "Cloche";
        hat13.color = "Pink";
        hat13.material = "Felt";
        hat13.brand = "Vintage";
        hat13.price = 25.00;
        hat13.isAdjustable = false;
        System.out.println("Hat 13: ");
        System.out.println("Hat ID: " + hat13.hatId);
        System.out.println("Style: " + hat13.style);
        System.out.println("Color: " + hat13.color);
        System.out.println("Material: " + hat13.material);
        System.out.println("Brand: " + hat13.brand);
        System.out.println("Price: " + hat13.price);
        System.out.println("Is Adjustable: " + hat13.isAdjustable);
        System.out.println();

        Hat hat14 = new Hat();
        hat14.hatId = 214;
        hat14.style = "Boater";
        hat14.color = "Navy Blue";
        hat14.material = "Straw";
        hat14.brand = "Classic";
        hat14.price = 27.50;
        hat14.isAdjustable = false;
        System.out.println("Hat 14: ");
        System.out.println("Hat ID: " + hat14.hatId);
        System.out.println("Style: " + hat14.style);
        System.out.println("Color: " + hat14.color);
        System.out.println("Material: " + hat14.material);
        System.out.println("Brand: " + hat14.brand);
        System.out.println("Price: " + hat14.price);
        System.out.println("Is Adjustable: " + hat14.isAdjustable);
        System.out.println();

        Hat hat15 = new Hat();
        hat15.hatId = 215;
        hat15.style = "Newsboy";
        hat15.color = "Gray";
        hat15.material = "Wool Blend";
        hat15.brand = "Retro";
        hat15.price = 32.00;
        hat15.isAdjustable = true;
        System.out.println("Hat 15: ");
        System.out.println("Hat ID: " + hat15.hatId);
        System.out.println("Style: " + hat15.style);
        System.out.println("Color: " + hat15.color);
        System.out.println("Material: " + hat15.material);
        System.out.println("Brand: " + hat15.brand);
        System.out.println("Price: " + hat15.price);
        System.out.println("Is Adjustable: " + hat15.isAdjustable);
        System.out.println();

        Hat hat16 = new Hat();
        hat16.hatId = 216;
        hat16.style = "Safari";
        hat16.color = "Khaki";
        hat16.material = "Cotton";
        hat16.brand = "Explorer";
        hat16.price = 40.00;
        hat16.isAdjustable = true;
        System.out.println("Hat 16: ");
        System.out.println("Hat ID: " + hat16.hatId);
        System.out.println("Style: " + hat16.style);
        System.out.println("Color: " + hat16.color);
        System.out.println("Material: " + hat16.material);
        System.out.println("Brand: " + hat16.brand);
        System.out.println("Price: " + hat16.price);
        System.out.println("Is Adjustable: " + hat16.isAdjustable);
        System.out.println();

        Hat hat17 = new Hat();
        hat17.hatId = 217;
        hat17.style = "Fedora";
        hat17.color = "Cream";
        hat17.material = "Felt";
        hat17.brand = "Stylish";
        hat17.price = 50.00;
        hat17.isAdjustable = false;
        System.out.println("Hat 17: ");
        System.out.println("Hat ID: " + hat17.hatId);
        System.out.println("Style: " + hat17.style);
        System.out.println("Color: " + hat17.color);
        System.out.println("Material: " + hat17.material);
        System.out.println("Brand: " + hat17.brand);
        System.out.println("Price: " + hat17.price);
        System.out.println("Is Adjustable: " + hat17.isAdjustable);
        System.out.println();

        Hat hat18 = new Hat();
        hat18.hatId = 218;
        hat18.style = "Sun Visor";
        hat18.color = "Pink";
        hat18.material = "Plastic";
        hat18.brand = "Sporty";
        hat18.price = 9.99;
        hat18.isAdjustable = true;
        System.out.println("Hat 18: ");
        System.out.println("Hat ID: " + hat18.hatId);
        System.out.println("Style: " + hat18.style);
        System.out.println("Color: " + hat18.color);
        System.out.println("Material: " + hat18.material);
        System.out.println("Brand: " + hat18.brand);
        System.out.println("Price: " + hat18.price);
        System.out.println("Is Adjustable: " + hat18.isAdjustable);
        System.out.println();

        Hat hat19 = new Hat();
        hat19.hatId = 219;
        hat19.style = "Cloche";
        hat19.color = "Purple";
        hat19.material = "Wool";
        hat19.brand = "Vintage";
        hat19.price = 28.00;
        hat19.isAdjustable = false;
        System.out.println("Hat 19: ");
        System.out.println("Hat ID: " + hat19.hatId);
        System.out.println("Style: " + hat19.style);
        System.out.println("Color: " + hat19.color);
        System.out.println("Material: " + hat19.material);
        System.out.println("Brand: " + hat19.brand);
        System.out.println("Price: " + hat19.price);
        System.out.println("Is Adjustable: " + hat19.isAdjustable);
        System.out.println();

        Hat hat20 = new Hat();
        hat20.hatId = 220;
        hat20.style = "Baseball";
        hat20.color = "Green";
        hat20.material = "Polyester";
        hat20.brand = "Adidas";
        hat20.price = 17.50;
        hat20.isAdjustable = true;
        System.out.println("Hat 20: ");
        System.out.println("Hat ID: " + hat20.hatId);
        System.out.println("Style: " + hat20.style);
        System.out.println("Color: " + hat20.color);
        System.out.println("Material: " + hat20.material);
        System.out.println("Brand: " + hat20.brand);
        System.out.println("Price: " + hat20.price);
        System.out.println("Is Adjustable: " + hat20.isAdjustable);
        System.out.println();

    }
}
