class InvitationCardRunner {
    public static void main(String[] args) {

        InvitationCard card1 = new InvitationCard();
        card1.cardId = 101;
        card1.occasion = "Wedding";
        card1.color = "Gold";
        card1.material = "Velvet";
        card1.senderName = "Anil";
        card1.price = 25.0;
        card1.isHandmade = true;
        System.out.println("Card 1: ");
        System.out.println("Card ID: " + card1.cardId);
        System.out.println("Occasion: " + card1.occasion);
        System.out.println("Color: " + card1.color);
        System.out.println("Material: " + card1.material);
        System.out.println("Sender Name: " + card1.senderName);
        System.out.println("Price: " + card1.price);
        System.out.println("Is Handmade: " + card1.isHandmade);
        System.out.println();

        InvitationCard card2 = new InvitationCard();
        card2.cardId = 102;
        card2.occasion = "Birthday";
        card2.color = "Pink";
        card2.material = "Paper";
        card2.senderName = "Kavya";
        card2.price = 15.0;
        card2.isHandmade = false;
        System.out.println("Card 2: ");
        System.out.println("Card ID: " + card2.cardId);
        System.out.println("Occasion: " + card2.occasion);
        System.out.println("Color: " + card2.color);
        System.out.println("Material: " + card2.material);
        System.out.println("Sender Name: " + card2.senderName);
        System.out.println("Price: " + card2.price);
        System.out.println("Is Handmade: " + card2.isHandmade);
        System.out.println();

        InvitationCard card3 = new InvitationCard();
        card3.cardId = 103;
        card3.occasion = "Baby Shower";
        card3.color = "Blue";
        card3.material = "Fabric";
        card3.senderName = "Divya";
        card3.price = 18.5;
        card3.isHandmade = true;
        System.out.println("Card 3: ");
        System.out.println("Card ID: " + card3.cardId);
        System.out.println("Occasion: " + card3.occasion);
        System.out.println("Color: " + card3.color);
        System.out.println("Material: " + card3.material);
        System.out.println("Sender Name: " + card3.senderName);
        System.out.println("Price: " + card3.price);
        System.out.println("Is Handmade: " + card3.isHandmade);
        System.out.println();

        InvitationCard card4 = new InvitationCard();
        card4.cardId = 104;
        card4.occasion = "Anniversary";
        card4.color = "Red";
        card4.material = "Leather";
        card4.senderName = "Ravi";
        card4.price = 22.0;
        card4.isHandmade = false;
        System.out.println("Card 4: ");
        System.out.println("Card ID: " + card4.cardId);
        System.out.println("Occasion: " + card4.occasion);
        System.out.println("Color: " + card4.color);
        System.out.println("Material: " + card4.material);
        System.out.println("Sender Name: " + card4.senderName);
        System.out.println("Price: " + card4.price);
        System.out.println("Is Handmade: " + card4.isHandmade);
        System.out.println();

        InvitationCard card5 = new InvitationCard();
        card5.cardId = 105;
        card5.occasion = "Engagement";
        card5.color = "Purple";
        card5.material = "Silk";
        card5.senderName = "Sneha";
        card5.price = 30.0;
        card5.isHandmade = true;
        System.out.println("Card 5: ");
        System.out.println("Card ID: " + card5.cardId);
        System.out.println("Occasion: " + card5.occasion);
        System.out.println("Color: " + card5.color);
        System.out.println("Material: " + card5.material);
        System.out.println("Sender Name: " + card5.senderName);
        System.out.println("Price: " + card5.price);
        System.out.println("Is Handmade: " + card5.isHandmade);
        System.out.println();

        InvitationCard card6 = new InvitationCard();
        card6.cardId = 106;
        card6.occasion = "Housewarming";
        card6.color = "White";
        card6.material = "Cardboard";
        card6.senderName = "Anita";
        card6.price = 12.5;
        card6.isHandmade = false;
        System.out.println("Card 6: ");
        System.out.println("Card ID: " + card6.cardId);
        System.out.println("Occasion: " + card6.occasion);
        System.out.println("Color: " + card6.color);
        System.out.println("Material: " + card6.material);
        System.out.println("Sender Name: " + card6.senderName);
        System.out.println("Price: " + card6.price);
        System.out.println("Is Handmade: " + card6.isHandmade);
        System.out.println();

        InvitationCard card7 = new InvitationCard();
        card7.cardId = 107;
        card7.occasion = "Farewell";
        card7.color = "Yellow";
        card7.material = "Cotton";
        card7.senderName = "Rahul";
        card7.price = 14.0;
        card7.isHandmade = true;
        System.out.println("Card 7: ");
        System.out.println("Card ID: " + card7.cardId);
        System.out.println("Occasion: " + card7.occasion);
        System.out.println("Color: " + card7.color);
        System.out.println("Material: " + card7.material);
        System.out.println("Sender Name: " + card7.senderName);
        System.out.println("Price: " + card7.price);
        System.out.println("Is Handmade: " + card7.isHandmade);
        System.out.println();

        InvitationCard card8 = new InvitationCard();
        card8.cardId = 108;
        card8.occasion = "Graduation";
        card8.color = "Green";
        card8.material = "Linen";
        card8.senderName = "Sonia";
        card8.price = 20.0;
        card8.isHandmade = false;
        System.out.println("Card 8: ");
        System.out.println("Card ID: " + card8.cardId);
        System.out.println("Occasion: " + card8.occasion);
        System.out.println("Color: " + card8.color);
        System.out.println("Material: " + card8.material);
        System.out.println("Sender Name: " + card8.senderName);
        System.out.println("Price: " + card8.price);
        System.out.println("Is Handmade: " + card8.isHandmade);
        System.out.println();

        InvitationCard card9 = new InvitationCard();
        card9.cardId = 109;
        card9.occasion = "Retirement";
        card9.color = "Beige";
        card9.material = "Canvas";
        card9.senderName = "Manoj";
        card9.price = 23.0;
        card9.isHandmade = true;
        System.out.println("Card 9: ");
        System.out.println("Card ID: " + card9.cardId);
        System.out.println("Occasion: " + card9.occasion);
        System.out.println("Color: " + card9.color);
        System.out.println("Material: " + card9.material);
        System.out.println("Sender Name: " + card9.senderName);
        System.out.println("Price: " + card9.price);
        System.out.println("Is Handmade: " + card9.isHandmade);
        System.out.println();

        InvitationCard card10 = new InvitationCard();
        card10.cardId = 110;
        card10.occasion = "Festival";
        card10.color = "Orange";
        card10.material = "Art Paper";
        card10.senderName = "Ramesh";
        card10.price = 19.0;
        card10.isHandmade = false;
        System.out.println("Card 10: ");
        System.out.println("Card ID: " + card10.cardId);
        System.out.println("Occasion: " + card10.occasion);
        System.out.println("Color: " + card10.color);
        System.out.println("Material: " + card10.material);
        System.out.println("Sender Name: " + card10.senderName);
        System.out.println("Price: " + card10.price);
        System.out.println("Is Handmade: " + card10.isHandmade);
        System.out.println();

                InvitationCard card11 = new InvitationCard();
        card11.cardId = 111;
        card11.occasion = "Inauguration";
        card11.color = "Silver";
        card11.material = "Glossy Paper";
        card11.senderName = "Deepak";
        card11.price = 27.0;
        card11.isHandmade = true;
        System.out.println("Card 11: ");
        System.out.println("Card ID: " + card11.cardId);
        System.out.println("Occasion: " + card11.occasion);
        System.out.println("Color: " + card11.color);
        System.out.println("Material: " + card11.material);
        System.out.println("Sender Name: " + card11.senderName);
        System.out.println("Price: " + card11.price);
        System.out.println("Is Handmade: " + card11.isHandmade);
        System.out.println();

        InvitationCard card12 = new InvitationCard();
        card12.cardId = 112;
        card12.occasion = "Welcome Party";
        card12.color = "Maroon";
        card12.material = "Silk Paper";
        card12.senderName = "Lakshmi";
        card12.price = 21.0;
        card12.isHandmade = false;
        System.out.println("Card 12: ");
        System.out.println("Card ID: " + card12.cardId);
        System.out.println("Occasion: " + card12.occasion);
        System.out.println("Color: " + card12.color);
        System.out.println("Material: " + card12.material);
        System.out.println("Sender Name: " + card12.senderName);
        System.out.println("Price: " + card12.price);
        System.out.println("Is Handmade: " + card12.isHandmade);
        System.out.println();

        InvitationCard card13 = new InvitationCard();
        card13.cardId = 113;
        card13.occasion = "Graduation Ceremony";
        card13.color = "Sky Blue";
        card13.material = "Hard Card";
        card13.senderName = "Rajesh";
        card13.price = 20.5;
        card13.isHandmade = true;
        System.out.println("Card 13: ");
        System.out.println("Card ID: " + card13.cardId);
        System.out.println("Occasion: " + card13.occasion);
        System.out.println("Color: " + card13.color);
        System.out.println("Material: " + card13.material);
        System.out.println("Sender Name: " + card13.senderName);
        System.out.println("Price: " + card13.price);
        System.out.println("Is Handmade: " + card13.isHandmade);
        System.out.println();

        InvitationCard card14 = new InvitationCard();
        card14.cardId = 114;
        card14.occasion = "Get Together";
        card14.color = "Teal";
        card14.material = "Matte Paper";
        card14.senderName = "Shruti";
        card14.price = 18.0;
        card14.isHandmade = false;
        System.out.println("Card 14: ");
        System.out.println("Card ID: " + card14.cardId);
        System.out.println("Occasion: " + card14.occasion);
        System.out.println("Color: " + card14.color);
        System.out.println("Material: " + card14.material);
        System.out.println("Sender Name: " + card14.senderName);
        System.out.println("Price: " + card14.price);
        System.out.println("Is Handmade: " + card14.isHandmade);
        System.out.println();

        InvitationCard card15 = new InvitationCard();
        card15.cardId = 115;
        card15.occasion = "Reception";
        card15.color = "Lavender";
        card15.material = "Foam";
        card15.senderName = "Tarun";
        card15.price = 32.0;
        card15.isHandmade = true;
        System.out.println("Card 15: ");
        System.out.println("Card ID: " + card15.cardId);
        System.out.println("Occasion: " + card15.occasion);
        System.out.println("Color: " + card15.color);
        System.out.println("Material: " + card15.material);
        System.out.println("Sender Name: " + card15.senderName);
        System.out.println("Price: " + card15.price);
        System.out.println("Is Handmade: " + card15.isHandmade);
        System.out.println();

        InvitationCard card16 = new InvitationCard();
        card16.cardId = 116;
        card16.occasion = "Bridal Shower";
        card16.color = "Coral";
        card16.material = "Embossed Card";
        card16.senderName = "Neha";
        card16.price = 26.5;
        card16.isHandmade = false;
        System.out.println("Card 16: ");
        System.out.println("Card ID: " + card16.cardId);
        System.out.println("Occasion: " + card16.occasion);
        System.out.println("Color: " + card16.color);
        System.out.println("Material: " + card16.material);
        System.out.println("Sender Name: " + card16.senderName);
        System.out.println("Price: " + card16.price);
        System.out.println("Is Handmade: " + card16.isHandmade);
        System.out.println();

        InvitationCard card17 = new InvitationCard();
        card17.cardId = 117;
        card17.occasion = "Naming Ceremony";
        card17.color = "Mint Green";
        card17.material = "Velvet Touch";
        card17.senderName = "Ajay";
        card17.price = 29.0;
        card17.isHandmade = true;
        System.out.println("Card 17: ");
        System.out.println("Card ID: " + card17.cardId);
        System.out.println("Occasion: " + card17.occasion);
        System.out.println("Color: " + card17.color);
        System.out.println("Material: " + card17.material);
        System.out.println("Sender Name: " + card17.senderName);
        System.out.println("Price: " + card17.price);
        System.out.println("Is Handmade: " + card17.isHandmade);
        System.out.println();

        InvitationCard card18 = new InvitationCard();
        card18.cardId = 118;
        card18.occasion = "Festival Greeting";
        card18.color = "Crimson";
        card18.material = "Shiny Board";
        card18.senderName = "Bhavna";
        card18.price = 16.0;
        card18.isHandmade = false;
        System.out.println("Card 18: ");
        System.out.println("Card ID: " + card18.cardId);
        System.out.println("Occasion: " + card18.occasion);
        System.out.println("Color: " + card18.color);
        System.out.println("Material: " + card18.material);
        System.out.println("Sender Name: " + card18.senderName);
        System.out.println("Price: " + card18.price);
        System.out.println("Is Handmade: " + card18.isHandmade);
        System.out.println();

        InvitationCard card19 = new InvitationCard();
        card19.cardId = 119;
        card19.occasion = "Promotion Celebration";
        card19.color = "Champagne";
        card19.material = "Gloss Board";
        card19.senderName = "Kiran";
        card19.price = 24.5;
        card19.isHandmade = true;
        System.out.println("Card 19: ");
        System.out.println("Card ID: " + card19.cardId);
        System.out.println("Occasion: " + card19.occasion);
        System.out.println("Color: " + card19.color);
        System.out.println("Material: " + card19.material);
        System.out.println("Sender Name: " + card19.senderName);
        System.out.println("Price: " + card19.price);
        System.out.println("Is Handmade: " + card19.isHandmade);
        System.out.println();

        InvitationCard card20 = new InvitationCard();
        card20.cardId = 120;
        card20.occasion = "Kitty Party";
        card20.color = "Turquoise";
        card20.material = "Soft Texture";
        card20.senderName = "Pooja";
        card20.price = 17.0;
        card20.isHandmade = false;
        System.out.println("Card 20: ");
        System.out.println("Card ID: " + card20.cardId);
        System.out.println("Occasion: " + card20.occasion);
        System.out.println("Color: " + card20.color);
        System.out.println("Material: " + card20.material);
        System.out.println("Sender Name: " + card20.senderName);
        System.out.println("Price: " + card20.price);
        System.out.println("Is Handmade: " + card20.isHandmade);
        System.out.println();

    }
}
 