 class JewelryRunner {
    public static void main(String[] args) {
        Jewelry jewelry1 = new Jewelry();
        jewelry1.jewelryId = 101;
        jewelry1.type = "Necklace";
        jewelry1.material = "Gold";
        jewelry1.color = "Yellow";
        jewelry1.brand = "Tanishq";
        jewelry1.price = 15000;
        jewelry1.gender = "Female";
        System.out.println("Jewelry ID: " + jewelry1.jewelryId);
        System.out.println("Type: " + jewelry1.type);
        System.out.println("Material: " + jewelry1.material);
        System.out.println("Color: " + jewelry1.color);
        System.out.println("Brand: " + jewelry1.brand);
        System.out.println("Price: " + jewelry1.price);
        System.out.println("Gender: " + jewelry1.gender);

        Jewelry jewelry2 = new Jewelry();
        jewelry2.jewelryId = 102;
        jewelry2.type = "Ring";
        jewelry2.material = "Silver";
        jewelry2.color = "Silver";
        jewelry2.brand = "Malabar";
        jewelry2.price = 2500;
        jewelry2.gender = "Unisex";
        System.out.println("Jewelry ID: " + jewelry2.jewelryId);
        System.out.println("Type: " + jewelry2.type);
        System.out.println("Material: " + jewelry2.material);
        System.out.println("Color: " + jewelry2.color);
        System.out.println("Brand: " + jewelry2.brand);
        System.out.println("Price: " + jewelry2.price);
        System.out.println("Gender: " + jewelry2.gender);

        Jewelry jewelry3 = new Jewelry();
        jewelry3.jewelryId = 103;
        jewelry3.type = "Bracelet";
        jewelry3.material = "Platinum";
        jewelry3.color = "White";
        jewelry3.brand = "Kalyan";
        jewelry3.price = 8000;
        jewelry3.gender = "Male";
        System.out.println("Jewelry ID: " + jewelry3.jewelryId);
        System.out.println("Type: " + jewelry3.type);
        System.out.println("Material: " + jewelry3.material);
        System.out.println("Color: " + jewelry3.color);
        System.out.println("Brand: " + jewelry3.brand);
        System.out.println("Price: " + jewelry3.price);
        System.out.println("Gender: " + jewelry3.gender);

        Jewelry jewelry4 = new Jewelry();
        jewelry4.jewelryId = 104;
        jewelry4.type = "Earrings";
        jewelry4.material = "Diamond";
        jewelry4.color = "Clear";
        jewelry4.brand = "TBZ";
        jewelry4.price = 12000;
        jewelry4.gender = "Female";
        System.out.println("Jewelry ID: " + jewelry4.jewelryId);
        System.out.println("Type: " + jewelry4.type);
        System.out.println("Material: " + jewelry4.material);
        System.out.println("Color: " + jewelry4.color);
        System.out.println("Brand: " + jewelry4.brand);
        System.out.println("Price: " + jewelry4.price);
        System.out.println("Gender: " + jewelry4.gender);

        Jewelry jewelry5 = new Jewelry();
        jewelry5.jewelryId = 105;
        jewelry5.type = "Bangles";
        jewelry5.material = "Gold";
        jewelry5.color = "Yellow";
        jewelry5.brand = "Jos Alukkas";
        jewelry5.price = 6000;
        jewelry5.gender = "Female";
        System.out.println("Jewelry ID: " + jewelry5.jewelryId);
        System.out.println("Type: " + jewelry5.type);
        System.out.println("Material: " + jewelry5.material);
        System.out.println("Color: " + jewelry5.color);
        System.out.println("Brand: " + jewelry5.brand);
        System.out.println("Price: " + jewelry5.price);
        System.out.println("Gender: " + jewelry5.gender);

        Jewelry jewelry6 = new Jewelry();
        jewelry6.jewelryId = 106;
        jewelry6.type = "Pendant";
        jewelry6.material = "Diamond";
        jewelry6.color = "Silver";
        jewelry6.brand = "Bluestone";
        jewelry6.price = 10000;
        jewelry6.gender = "Unisex";
        System.out.println("Jewelry ID: " + jewelry6.jewelryId);
        System.out.println("Type: " + jewelry6.type);
        System.out.println("Material: " + jewelry6.material);
        System.out.println("Color: " + jewelry6.color);
        System.out.println("Brand: " + jewelry6.brand);
        System.out.println("Price: " + jewelry6.price);
        System.out.println("Gender: " + jewelry6.gender);

        Jewelry jewelry7 = new Jewelry();
        jewelry7.jewelryId = 107;
        jewelry7.type = "Nose Ring";
        jewelry7.material = "Gold";
        jewelry7.color = "Yellow";
        jewelry7.brand = "CaratLane";
        jewelry7.price = 1500;
        jewelry7.gender = "Female";
        System.out.println("Jewelry ID: " + jewelry7.jewelryId);
        System.out.println("Type: " + jewelry7.type);
        System.out.println("Material: " + jewelry7.material);
        System.out.println("Color: " + jewelry7.color);
        System.out.println("Brand: " + jewelry7.brand);
        System.out.println("Price: " + jewelry7.price);
        System.out.println("Gender: " + jewelry7.gender);

        Jewelry jewelry8 = new Jewelry();
        jewelry8.jewelryId = 108;
        jewelry8.type = "Anklet";
        jewelry8.material = "Silver";
        jewelry8.color = "Silver";
        jewelry8.brand = "Trendy";
        jewelry8.price = 2000;
        jewelry8.gender = "Female";
        System.out.println("Jewelry ID: " + jewelry8.jewelryId);
        System.out.println("Type: " + jewelry8.type);
        System.out.println("Material: " + jewelry8.material);
        System.out.println("Color: " + jewelry8.color);
        System.out.println("Brand: " + jewelry8.brand);
        System.out.println("Price: " + jewelry8.price);
        System.out.println("Gender: " + jewelry8.gender);

        Jewelry jewelry9 = new Jewelry();
        jewelry9.jewelryId = 109;
        jewelry9.type = "Chain";
        jewelry9.material = "Platinum";
        jewelry9.color = "White";
        jewelry9.brand = "Reliance";
        jewelry9.price = 11000;
        jewelry9.gender = "Male";
        System.out.println("Jewelry ID: " + jewelry9.jewelryId);
        System.out.println("Type: " + jewelry9.type);
        System.out.println("Material: " + jewelry9.material);
        System.out.println("Color: " + jewelry9.color);
        System.out.println("Brand: " + jewelry9.brand);
        System.out.println("Price: " + jewelry9.price);
        System.out.println("Gender: " + jewelry9.gender);

        Jewelry jewelry10 = new Jewelry();
        jewelry10.jewelryId = 110;
        jewelry10.type = "Brooch";
        jewelry10.material = "Gold";
        jewelry10.color = "Gold";
        jewelry10.brand = "Classic Touch";
        jewelry10.price = 3500;
        jewelry10.gender = "Unisex";
        System.out.println("Jewelry ID: " + jewelry10.jewelryId);
        System.out.println("Type: " + jewelry10.type);
        System.out.println("Material: " + jewelry10.material);
        System.out.println("Color: " + jewelry10.color);
        System.out.println("Brand: " + jewelry10.brand);
        System.out.println("Price: " + jewelry10.price);
        System.out.println("Gender: " + jewelry10.gender);
		Jewelry jewelry11 = new Jewelry();
jewelry11.jewelryId = 111;
jewelry11.type = "Earring";
jewelry11.material = "Platinum";
jewelry11.design = "Peacock";
jewelry11.weight = 9.4;
jewelry11.purity = "99.99%";
jewelry11.gender = "Female";

Jewelry jewelry12 = new Jewelry();
jewelry12.jewelryId = 112;
jewelry12.type = "Necklace";
jewelry12.material = "Gold";
jewelry12.design = "Leafy";
jewelry12.weight = 18.7;
jewelry12.purity = "91.6%";
jewelry12.gender = "Unisex";

Jewelry jewelry13 = new Jewelry();
jewelry13.jewelryId = 113;
jewelry13.type = "Bangle";
jewelry13.material = "Silver";
jewelry13.design = "Zigzag";
jewelry13.weight = 14.3;
jewelry13.purity = "92.5%";
jewelry13.gender = "Female";

Jewelry jewelry14 = new Jewelry();
jewelry14.jewelryId = 114;
jewelry14.type = "Ring";
jewelry14.material = "Titanium";
jewelry14.design = "Flat";
jewelry14.weight = 5.6;
jewelry14.purity = "High";
jewelry14.gender = "Male";

Jewelry jewelry15 = new Jewelry();
jewelry15.jewelryId = 115;
jewelry15.type = "Bracelet";
jewelry15.material = "Copper";
jewelry15.design = "Braided";
jewelry15.weight = 7.1;
jewelry15.purity = "Fine";
jewelry15.gender = "Unisex";

Jewelry jewelry16 = new Jewelry();
jewelry16.jewelryId = 116;
jewelry16.type = "Pendant";
jewelry16.material = "Silver";
jewelry16.design = "Cross";
jewelry16.weight = 3.8;
jewelry16.purity = "92.5%";
jewelry16.gender = "Female";

Jewelry jewelry17 = new Jewelry();
jewelry17.jewelryId = 117;
jewelry17.type = "Chain";
jewelry17.material = "Gold";
jewelry17.design = "Box";
jewelry17.weight = 13.2;
jewelry17.purity = "22K";
jewelry17.gender = "Male";

Jewelry jewelry18 = new Jewelry();
jewelry18.jewelryId = 118;
jewelry18.type = "Anklet";
jewelry18.material = "Silver";
jewelry18.design = "Round";
jewelry18.weight = 8.6;
jewelry18.purity = "92.5%";
jewelry18.gender = "Female";

Jewelry jewelry19 = new Jewelry();
jewelry19.jewelryId = 119;
jewelry19.type = "Earring";
jewelry19.material = "Rose Gold";
jewelry19.design = "Tear Drop";
jewelry19.weight = 4.9;
jewelry19.purity = "18K";
jewelry19.gender = "Female";

Jewelry jewelry20 = new Jewelry();
jewelry20.jewelryId = 120;
jewelry20.type = "Ring";
jewelry20.material = "Platinum";
jewelry20.design = "Classic";
jewelry20.weight = 6.5;
jewelry20.purity = "99.9%";
jewelry20.gender = "Unisex";

    }
}
