class NetworkRunner {
    public static void main(String[] args) {

        NetworkDevice device1 = new NetworkDevice();
        device1.deviceId = 401;
        device1.deviceType = "Router";
        device1.ipAddress = "192.168.1.1";
        device1.macAddress = "00:1A:2B:3C:4D:5E";
        device1.manufacturer = "Cisco";
        device1.bandwidth = 1000.0;
        device1.isWireless = true;
        System.out.println("Device 1: ");
        System.out.println("Device ID: " + device1.deviceId);
        System.out.println("Device Type: " + device1.deviceType);
        System.out.println("IP Address: " + device1.ipAddress);
        System.out.println("MAC Address: " + device1.macAddress);
        System.out.println("Manufacturer: " + device1.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device1.bandwidth);
        System.out.println("Is Wireless: " + device1.isWireless);
        System.out.println();

        NetworkDevice device2 = new NetworkDevice();
        device2.deviceId = 402;
        device2.deviceType = "Switch";
        device2.ipAddress = "192.168.1.2";
        device2.macAddress = "00:1B:2C:3D:4E:5F";
        device2.manufacturer = "Netgear";
        device2.bandwidth = 100.0;
        device2.isWireless = false;
        System.out.println("Device 2: ");
        System.out.println("Device ID: " + device2.deviceId);
        System.out.println("Device Type: " + device2.deviceType);
        System.out.println("IP Address: " + device2.ipAddress);
        System.out.println("MAC Address: " + device2.macAddress);
        System.out.println("Manufacturer: " + device2.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device2.bandwidth);
        System.out.println("Is Wireless: " + device2.isWireless);
        System.out.println();

        NetworkDevice device3 = new NetworkDevice();
        device3.deviceId = 403;
        device3.deviceType = "Access Point";
        device3.ipAddress = "192.168.1.3";
        device3.macAddress = "00:1C:2D:3E:4F:5G";
        device3.manufacturer = "TP-Link";
        device3.bandwidth = 300.0;
        device3.isWireless = true;
        System.out.println("Device 3: ");
        System.out.println("Device ID: " + device3.deviceId);
        System.out.println("Device Type: " + device3.deviceType);
        System.out.println("IP Address: " + device3.ipAddress);
        System.out.println("MAC Address: " + device3.macAddress);
        System.out.println("Manufacturer: " + device3.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device3.bandwidth);
        System.out.println("Is Wireless: " + device3.isWireless);
        System.out.println();

        NetworkDevice device4 = new NetworkDevice();
        device4.deviceId = 404;
        device4.deviceType = "Modem";
        device4.ipAddress = "192.168.1.4";
        device4.macAddress = "00:1D:2E:3F:4G:5H";
        device4.manufacturer = "Motorola";
        device4.bandwidth = 150.0;
        device4.isWireless = false;
        System.out.println("Device 4: ");
        System.out.println("Device ID: " + device4.deviceId);
        System.out.println("Device Type: " + device4.deviceType);
        System.out.println("IP Address: " + device4.ipAddress);
        System.out.println("MAC Address: " + device4.macAddress);
        System.out.println("Manufacturer: " + device4.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device4.bandwidth);
        System.out.println("Is Wireless: " + device4.isWireless);
        System.out.println();

        NetworkDevice device5 = new NetworkDevice();
        device5.deviceId = 405;
        device5.deviceType = "Firewall";
        device5.ipAddress = "192.168.1.5";
        device5.macAddress = "00:1E:2F:3G:4H:5I";
        device5.manufacturer = "Fortinet";
        device5.bandwidth = 500.0;
        device5.isWireless = false;
        System.out.println("Device 5: ");
        System.out.println("Device ID: " + device5.deviceId);
        System.out.println("Device Type: " + device5.deviceType);
        System.out.println("IP Address: " + device5.ipAddress);
        System.out.println("MAC Address: " + device5.macAddress);
        System.out.println("Manufacturer: " + device5.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device5.bandwidth);
        System.out.println("Is Wireless: " + device5.isWireless);
        System.out.println();

        NetworkDevice device6 = new NetworkDevice();
        device6.deviceId = 406;
        device6.deviceType = "Router";
        device6.ipAddress = "192.168.2.1";
        device6.macAddress = "00:1F:2G:3H:4I:5J";
        device6.manufacturer = "Cisco";
        device6.bandwidth = 1200.0;
        device6.isWireless = true;
        System.out.println("Device 6: ");
        System.out.println("Device ID: " + device6.deviceId);
        System.out.println("Device Type: " + device6.deviceType);
        System.out.println("IP Address: " + device6.ipAddress);
        System.out.println("MAC Address: " + device6.macAddress);
        System.out.println("Manufacturer: " + device6.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device6.bandwidth);
        System.out.println("Is Wireless: " + device6.isWireless);
        System.out.println();

        NetworkDevice device7 = new NetworkDevice();
        device7.deviceId = 407;
        device7.deviceType = "Switch";
        device7.ipAddress = "192.168.2.2";
        device7.macAddress = "00:2A:3B:4C:5D:6E";
        device7.manufacturer = "Netgear";
        device7.bandwidth = 200.0;
        device7.isWireless = false;
        System.out.println("Device 7: ");
        System.out.println("Device ID: " + device7.deviceId);
        System.out.println("Device Type: " + device7.deviceType);
        System.out.println("IP Address: " + device7.ipAddress);
        System.out.println("MAC Address: " + device7.macAddress);
        System.out.println("Manufacturer: " + device7.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device7.bandwidth);
        System.out.println("Is Wireless: " + device7.isWireless);
        System.out.println();

        NetworkDevice device8 = new NetworkDevice();
        device8.deviceId = 408;
        device8.deviceType = "Access Point";
        device8.ipAddress = "192.168.2.3";
        device8.macAddress = "00:2B:3C:4D:5E:6F";
        device8.manufacturer = "TP-Link";
        device8.bandwidth = 350.0;
        device8.isWireless = true;
        System.out.println("Device 8: ");
        System.out.println("Device ID: " + device8.deviceId);
        System.out.println("Device Type: " + device8.deviceType);
        System.out.println("IP Address: " + device8.ipAddress);
        System.out.println("MAC Address: " + device8.macAddress);
        System.out.println("Manufacturer: " + device8.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device8.bandwidth);
        System.out.println("Is Wireless: " + device8.isWireless);
        System.out.println();

        NetworkDevice device9 = new NetworkDevice();
        device9.deviceId = 409;
        device9.deviceType = "Modem";
        device9.ipAddress = "192.168.2.4";
        device9.macAddress = "00:2C:3D:4E:5F:6G";
        device9.manufacturer = "Motorola";
        device9.bandwidth = 180.0;
        device9.isWireless = false;
        System.out.println("Device 9: ");
        System.out.println("Device ID: " + device9.deviceId);
        System.out.println("Device Type: " + device9.deviceType);
        System.out.println("IP Address: " + device9.ipAddress);
        System.out.println("MAC Address: " + device9.macAddress);
        System.out.println("Manufacturer: " + device9.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device9.bandwidth);
        System.out.println("Is Wireless: " + device9.isWireless);
        System.out.println();

        NetworkDevice device10 = new NetworkDevice();
        device10.deviceId = 410;
        device10.deviceType = "Firewall";
        device10.ipAddress = "192.168.2.5";
        device10.macAddress = "00:2D:3E:4F:5G:6H";
        device10.manufacturer = "Fortinet";
        device10.bandwidth = 600.0;
        device10.isWireless = false;
        System.out.println("Device 10: ");
        System.out.println("Device ID: " + device10.deviceId);
        System.out.println("Device Type: " + device10.deviceType);
        System.out.println("IP Address: " + device10.ipAddress);
        System.out.println("MAC Address: " + device10.macAddress);
        System.out.println("Manufacturer: " + device10.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device10.bandwidth);
        System.out.println("Is Wireless: " + device10.isWireless);
        System.out.println();

               NetworkDevice device11 = new NetworkDevice();
        device11.deviceId = 411;
        device11.deviceType = "Router";
        device11.ipAddress = "10.0.0.1";
        device11.macAddress = "00:3A:4B:5C:6D:7E";
        device11.manufacturer = "Cisco";
        device11.bandwidth = 900.0;
        device11.isWireless = true;
        System.out.println("Device 11: ");
        System.out.println("Device ID: " + device11.deviceId);
        System.out.println("Device Type: " + device11.deviceType);
        System.out.println("IP Address: " + device11.ipAddress);
        System.out.println("MAC Address: " + device11.macAddress);
        System.out.println("Manufacturer: " + device11.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device11.bandwidth);
        System.out.println("Is Wireless: " + device11.isWireless);
        System.out.println();

        NetworkDevice device12 = new NetworkDevice();
        device12.deviceId = 412;
        device12.deviceType = "Switch";
        device12.ipAddress = "10.0.0.2";
        device12.macAddress = "00:3B:4C:5D:6E:7F";
        device12.manufacturer = "Netgear";
        device12.bandwidth = 250.0;
        device12.isWireless = false;
        System.out.println("Device 12: ");
        System.out.println("Device ID: " + device12.deviceId);
        System.out.println("Device Type: " + device12.deviceType);
        System.out.println("IP Address: " + device12.ipAddress);
        System.out.println("MAC Address: " + device12.macAddress);
        System.out.println("Manufacturer: " + device12.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device12.bandwidth);
        System.out.println("Is Wireless: " + device12.isWireless);
        System.out.println();

        NetworkDevice device13 = new NetworkDevice();
        device13.deviceId = 413;
        device13.deviceType = "Access Point";
        device13.ipAddress = "10.0.0.3";
        device13.macAddress = "00:3C:4D:5E:6F:7G";
        device13.manufacturer = "TP-Link";
        device13.bandwidth = 400.0;
        device13.isWireless = true;
        System.out.println("Device 13: ");
        System.out.println("Device ID: " + device13.deviceId);
        System.out.println("Device Type: " + device13.deviceType);
        System.out.println("IP Address: " + device13.ipAddress);
        System.out.println("MAC Address: " + device13.macAddress);
        System.out.println("Manufacturer: " + device13.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device13.bandwidth);
        System.out.println("Is Wireless: " + device13.isWireless);
        System.out.println();

        NetworkDevice device14 = new NetworkDevice();
        device14.deviceId = 414;
        device14.deviceType = "Modem";
        device14.ipAddress = "10.0.0.4";
        device14.macAddress = "00:3D:4E:5F:6G:7H";
        device14.manufacturer = "Motorola";
        device14.bandwidth = 220.0;
        device14.isWireless = false;
        System.out.println("Device 14: ");
        System.out.println("Device ID: " + device14.deviceId);
        System.out.println("Device Type: " + device14.deviceType);
        System.out.println("IP Address: " + device14.ipAddress);
        System.out.println("MAC Address: " + device14.macAddress);
        System.out.println("Manufacturer: " + device14.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device14.bandwidth);
        System.out.println("Is Wireless: " + device14.isWireless);
        System.out.println();

        NetworkDevice device15 = new NetworkDevice();
        device15.deviceId = 415;
        device15.deviceType = "Firewall";
        device15.ipAddress = "10.0.0.5";
        device15.macAddress = "00:3E:4F:5G:6H:7I";
        device15.manufacturer = "Fortinet";
        device15.bandwidth = 550.0;
        device15.isWireless = false;
        System.out.println("Device 15: ");
        System.out.println("Device ID: " + device15.deviceId);
        System.out.println("Device Type: " + device15.deviceType);
        System.out.println("IP Address: " + device15.ipAddress);
        System.out.println("MAC Address: " + device15.macAddress);
        System.out.println("Manufacturer: " + device15.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device15.bandwidth);
        System.out.println("Is Wireless: " + device15.isWireless);
        System.out.println();

        NetworkDevice device16 = new NetworkDevice();
        device16.deviceId = 416;
        device16.deviceType = "Router";
        device16.ipAddress = "172.16.0.1";
        device16.macAddress = "00:4A:5B:6C:7D:8E";
        device16.manufacturer = "Cisco";
        device16.bandwidth = 1100.0;
        device16.isWireless = true;
        System.out.println("Device 16: ");
        System.out.println("Device ID: " + device16.deviceId);
        System.out.println("Device Type: " + device16.deviceType);
        System.out.println("IP Address: " + device16.ipAddress);
        System.out.println("MAC Address: " + device16.macAddress);
        System.out.println("Manufacturer: " + device16.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device16.bandwidth);
        System.out.println("Is Wireless: " + device16.isWireless);
        System.out.println();

        NetworkDevice device17 = new NetworkDevice();
        device17.deviceId = 417;
        device17.deviceType = "Switch";
        device17.ipAddress = "172.16.0.2";
        device17.macAddress = "00:4B:5C:6D:7E:8F";
        device17.manufacturer = "Netgear";
        device17.bandwidth = 300.0;
        device17.isWireless = false;
        System.out.println("Device 17: ");
        System.out.println("Device ID: " + device17.deviceId);
        System.out.println("Device Type: " + device17.deviceType);
        System.out.println("IP Address: " + device17.ipAddress);
        System.out.println("MAC Address: " + device17.macAddress);
        System.out.println("Manufacturer: " + device17.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device17.bandwidth);
        System.out.println("Is Wireless: " + device17.isWireless);
        System.out.println();

        NetworkDevice device18 = new NetworkDevice();
        device18.deviceId = 418;
        device18.deviceType = "Access Point";
        device18.ipAddress = "172.16.0.3";
        device18.macAddress = "00:4C:5D:6E:7F:8G";
        device18.manufacturer = "TP-Link";
        device18.bandwidth = 450.0;
        device18.isWireless = true;
        System.out.println("Device 18: ");
        System.out.println("Device ID: " + device18.deviceId);
        System.out.println("Device Type: " + device18.deviceType);
        System.out.println("IP Address: " + device18.ipAddress);
        System.out.println("MAC Address: " + device18.macAddress);
        System.out.println("Manufacturer: " + device18.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device18.bandwidth);
        System.out.println("Is Wireless: " + device18.isWireless);
        System.out.println();

        NetworkDevice device19 = new NetworkDevice();
        device19.deviceId = 419;
        device19.deviceType = "Modem";
        device19.ipAddress = "172.16.0.4";
        device19.macAddress = "00:4D:5E:6F:7G:8H";
        device19.manufacturer = "Motorola";
        device19.bandwidth = 250.0;
        device19.isWireless = false;
        System.out.println("Device 19: ");
        System.out.println("Device ID: " + device19.deviceId);
        System.out.println("Device Type: " + device19.deviceType);
        System.out.println("IP Address: " + device19.ipAddress);
        System.out.println("MAC Address: " + device19.macAddress);
        System.out.println("Manufacturer: " + device19.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device19.bandwidth);
        System.out.println("Is Wireless: " + device19.isWireless);
        System.out.println();

        NetworkDevice device20 = new NetworkDevice();
        device20.deviceId = 420;
        device20.deviceType = "Firewall";
        device20.ipAddress = "172.16.0.5";
        device20.macAddress = "00:4E:5F:6G:7H:8I";
        device20.manufacturer = "Fortinet";
        device20.bandwidth = 650.0;
        device20.isWireless = false;
        System.out.println("Device 20: ");
        System.out.println("Device ID: " + device20.deviceId);
        System.out.println("Device Type: " + device20.deviceType);
        System.out.println("IP Address: " + device20.ipAddress);
        System.out.println("MAC Address: " + device20.macAddress);
        System.out.println("Manufacturer: " + device20.manufacturer);
        System.out.println("Bandwidth (Mbps): " + device20.bandwidth);
        System.out.println("Is Wireless: " + device20.isWireless);
        System.out.println();

    }
}
