class PipeRunner{


public static void main(STring[] pip){
Pipe pipe1 = new Pipe();
pipe1.pipeId = 501;
pipe1.material = "PVC";
pipe1.length = 10.5;
pipe1.diameter = 4.0;
pipe1.isInsulated = false;
pipe1.color = "White";
System.out.println("Pipe 1: ");
System.out.println("Pipe ID: " + pipe1.pipeId);
System.out.println("Material: " + pipe1.material);
System.out.println("Length (meters): " + pipe1.length);
System.out.println("Diameter (inches): " + pipe1.diameter);
System.out.println("Is Insulated: " + pipe1.isInsulated);
System.out.println("Color: " + pipe1.color);
System.out.println();

Pipe pipe2 = new Pipe();
pipe2.pipeId = 502;
pipe2.material = "Copper";
pipe2.length = 7.8;
pipe2.diameter = 2.5;
pipe2.isInsulated = true;
pipe2.color = "Copper";
System.out.println("Pipe 2: ");
System.out.println("Pipe ID: " + pipe2.pipeId);
System.out.println("Material: " + pipe2.material);
System.out.println("Length (meters): " + pipe2.length);
System.out.println("Diameter (inches): " + pipe2.diameter);
System.out.println("Is Insulated: " + pipe2.isInsulated);
System.out.println("Color: " + pipe2.color);
System.out.println();

Pipe pipe3 = new Pipe();
pipe3.pipeId = 503;
pipe3.material = "Steel";
pipe3.length = 15.0;
pipe3.diameter = 6.0;
pipe3.isInsulated = false;
pipe3.color = "Gray";
System.out.println("Pipe 3: ");
System.out.println("Pipe ID: " + pipe3.pipeId);
System.out.println("Material: " + pipe3.material);
System.out.println("Length (meters): " + pipe3.length);
System.out.println("Diameter (inches): " + pipe3.diameter);
System.out.println("Is Insulated: " + pipe3.isInsulated);
System.out.println("Color: " + pipe3.color);
System.out.println();

Pipe pipe4 = new Pipe();
pipe4.pipeId = 504;
pipe4.material = "HDPE";
pipe4.length = 12.3;
pipe4.diameter = 3.0;
pipe4.isInsulated = true;
pipe4.color = "Black";
System.out.println("Pipe 4: ");
System.out.println("Pipe ID: " + pipe4.pipeId);
System.out.println("Material: " + pipe4.material);
System.out.println("Length (meters): " + pipe4.length);
System.out.println("Diameter (inches): " + pipe4.diameter);
System.out.println("Is Insulated: " + pipe4.isInsulated);
System.out.println("Color: " + pipe4.color);
System.out.println();

Pipe pipe5 = new Pipe();
pipe5.pipeId = 505;
pipe5.material = "PVC";
pipe5.length = 9.0;
pipe5.diameter = 5.0;
pipe5.isInsulated = false;
pipe5.color = "Blue";
System.out.println("Pipe 5: ");
System.out.println("Pipe ID: " + pipe5.pipeId);
System.out.println("Material: " + pipe5.material);
System.out.println("Length (meters): " + pipe5.length);
System.out.println("Diameter (inches): " + pipe5.diameter);
System.out.println("Is Insulated: " + pipe5.isInsulated);
System.out.println("Color: " + pipe5.color);
System.out.println();

Pipe pipe6 = new Pipe();
pipe6.pipeId = 506;
pipe6.material = "Copper";
pipe6.length = 8.4;
pipe6.diameter = 2.0;
pipe6.isInsulated = true;
pipe6.color = "Copper";
System.out.println("Pipe 6: ");
System.out.println("Pipe ID: " + pipe6.pipeId);
System.out.println("Material: " + pipe6.material);
System.out.println("Length (meters): " + pipe6.length);
System.out.println("Diameter (inches): " + pipe6.diameter);
System.out.println("Is Insulated: " + pipe6.isInsulated);
System.out.println("Color: " + pipe6.color);
System.out.println();

Pipe pipe7 = new Pipe();
pipe7.pipeId = 507;
pipe7.material = "Steel";
pipe7.length = 20.0;
pipe7.diameter = 7.0;
pipe7.isInsulated = false;
pipe7.color = "Silver";
System.out.println("Pipe 7: ");
System.out.println("Pipe ID: " + pipe7.pipeId);
System.out.println("Material: " + pipe7.material);
System.out.println("Length (meters): " + pipe7.length);
System.out.println("Diameter (inches): " + pipe7.diameter);
System.out.println("Is Insulated: " + pipe7.isInsulated);
System.out.println("Color: " + pipe7.color);
System.out.println();

Pipe pipe8 = new Pipe();
pipe8.pipeId = 508;
pipe8.material = "HDPE";
pipe8.length = 11.1;
pipe8.diameter = 4.5;
pipe8.isInsulated = true;
pipe8.color = "Green";
System.out.println("Pipe 8: ");
System.out.println("Pipe ID: " + pipe8.pipeId);
System.out.println("Material: " + pipe8.material);
System.out.println("Length (meters): " + pipe8.length);
System.out.println("Diameter (inches): " + pipe8.diameter);
System.out.println("Is Insulated: " + pipe8.isInsulated);
System.out.println("Color: " + pipe8.color);
System.out.println();

Pipe pipe9 = new Pipe();
pipe9.pipeId = 509;
pipe9.material = "PVC";
pipe9.length = 14.0;
pipe9.diameter = 3.5;
pipe9.isInsulated = false;
pipe9.color = "White";
System.out.println("Pipe 9: ");
System.out.println("Pipe ID: " + pipe9.pipeId);
System.out.println("Material: " + pipe9.material);
System.out.println("Length (meters): " + pipe9.length);
System.out.println("Diameter (inches): " + pipe9.diameter);
System.out.println("Is Insulated: " + pipe9.isInsulated);
System.out.println("Color: " + pipe9.color);
System.out.println();

Pipe pipe10 = new Pipe();
pipe10.pipeId = 510;
pipe10.material = "Copper";
pipe10.length = 6.7;
pipe10.diameter = 2.8;
pipe10.isInsulated = true;
pipe10.color = "Copper";
System.out.println("Pipe 10: ");
System.out.println("Pipe ID: " + pipe10.pipeId);
System.out.println("Material: " + pipe10.material);
System.out.println("Length (meters): " + pipe10.length);
System.out.println("Diameter (inches): " + pipe10.diameter);
System.out.println("Is Insulated: " + pipe10.isInsulated);
System.out.println("Color: " + pipe10.color);
System.out.println();

Pipe pipe11 = new Pipe();
pipe11.pipeId = 511;
pipe11.material = "Steel";
pipe11.length = 18.0;
pipe11.diameter = 6.5;
pipe11.isInsulated = false;
pipe11.color = "Gray";
System.out.println("Pipe 11: ");
System.out.println("Pipe ID: " + pipe11.pipeId);
System.out.println("Material: " + pipe11.material);
System.out.println("Length (meters): " + pipe11.length);
System.out.println("Diameter (inches): " + pipe11.diameter);
System.out.println("Is Insulated: " + pipe11.isInsulated);
System.out.println("Color: " + pipe11.color);
System.out.println();

Pipe pipe12 = new Pipe();
pipe12.pipeId = 512;
pipe12.material = "HDPE";
pipe12.length = 13.2;
pipe12.diameter = 3.8;
pipe12.isInsulated = true;
pipe12.color = "Black";
System.out.println("Pipe 12: ");
System.out.println("Pipe ID: " + pipe12.pipeId);
System.out.println("Material: " + pipe12.material);
System.out.println("Length (meters): " + pipe12.length);
System.out.println("Diameter (inches): " + pipe12.diameter);
System.out.println("Is Insulated: " + pipe12.isInsulated);
System.out.println("Color: " + pipe12.color);
System.out.println();

Pipe pipe13 = new Pipe();
pipe13.pipeId = 513;
pipe13.material = "PVC";
pipe13.length = 9.7;
pipe13.diameter = 4.2;
pipe13.isInsulated = false;
pipe13.color = "Blue";
System.out.println("Pipe 13: ");
System.out.println("Pipe ID: " + pipe13.pipeId);
System.out.println("Material: " + pipe13.material);
System.out.println("Length (meters): " + pipe13.length);
System.out.println("Diameter (inches): " + pipe13.diameter);
System.out.println("Is Insulated: " + pipe13.isInsulated);
System.out.println("Color: " + pipe13.color);
System.out.println();

Pipe pipe14 = new Pipe();
pipe14.pipeId = 514;
pipe14.material = "Copper";
pipe14.length = 7.0;
pipe14.diameter = 2.7;
pipe14.isInsulated = true;
pipe14.color = "Copper";
System.out.println("Pipe 14: ");
System.out.println("Pipe ID: " + pipe14.pipeId);
System.out.println("Material: " + pipe14.material);
System.out.println("Length (meters): " + pipe14.length);
System.out.println("Diameter (inches): " + pipe14.diameter);
System.out.println("Is Insulated: " + pipe14.isInsulated);
System.out.println("Color: " + pipe14.color);
System.out.println();

Pipe pipe15 = new Pipe();
pipe15.pipeId = 515;
pipe15.material = "Steel";
pipe15.length = 16.5;
pipe15.diameter = 5.5;
pipe15.isInsulated = false;
pipe15.color = "Silver";
System.out.println("Pipe 15: ");
System.out.println("Pipe ID: " + pipe15.pipeId);
System.out.println("Material: " + pipe15.material);
System.out.println("Length (meters): " + pipe15.length);
System.out.println("Diameter (inches): " + pipe15.diameter);
System.out.println("Is Insulated: " + pipe15.isInsulated);
System.out.println("Color: " + pipe15.color);
System.out.println();

Pipe pipe16 = new Pipe();
pipe16.pipeId = 516;
pipe16.material = "HDPE";
pipe16.length = 14.4;
pipe16.diameter = 4.8;
pipe16.isInsulated = true;
pipe16.color = "Green";
System.out.println("Pipe 16: ");
System.out.println("Pipe ID: " + pipe16.pipeId);
System.out.println("Material: " + pipe16.material);
System.out.println("Length (meters): " + pipe16.length);
System.out.println("Diameter (inches): " + pipe16.diameter);
System.out.println("Is Insulated: " + pipe16.isInsulated);
System.out.println("Color: " + pipe16.color);
System.out.println();

Pipe pipe17 = new Pipe();
pipe17.pipeId = 517;
pipe17.material = "PVC";
pipe17.length = 12.0;
pipe17.diameter = 3.0;
pipe17.isInsulated = false;
pipe17.color = "White";
System.out.println("Pipe 17: ");
System.out.println("Pipe ID: " + pipe17.pipeId);
System.out.println("Material: " + pipe17.material);
System.out.println("Length (meters): " + pipe17.length);
System.out.println("Diameter (inches): " + pipe17.diameter);
System.out.println("Is Insulated: " + pipe17.isInsulated);
System.out.println("Color: " + pipe17.color);
System.out.println();

Pipe pipe18 = new Pipe();
pipe18.pipeId = 518;
pipe18.material = "Copper";
pipe18.length = 8.9;
pipe18.diameter = 2.9;
pipe18.isInsulated = true;
pipe18.color = "Copper";
System.out.println("Pipe 18: ");
System.out.println("Pipe ID: " + pipe18.pipeId);
System.out.println("Material: " + pipe18.material);
System.out.println("Length (meters): " + pipe18.length);
System.out.println("Diameter (inches): " + pipe18.diameter);
System.out.println("Is Insulated: " + pipe18.isInsulated);
System.out.println("Color: " + pipe18.color);
System.out.println();

Pipe pipe19 = new Pipe();
pipe19.pipeId = 519;
pipe19.material = "Steel";
pipe19.length = 19.3;
pipe19.diameter = 6.2;
pipe19.isInsulated = false;
pipe19.color = "Gray";
System.out.println("Pipe 19: ");
System.out.println("Pipe ID: " + pipe19.pipeId);
System.out.println("Material: " + pipe19.material);
System.out.println("Length (meters): " + pipe19.length);
System.out.println("Diameter (inches): " + pipe19.diameter);
System.out.println("Is Insulated: " + pipe19.isInsulated);
System.out.println("Color: " + pipe19.color);
System.out.println();

Pipe pipe20 = new Pipe();
pipe20.pipeId = 520;
pipe20.material = "HDPE";
pipe20.length = 15.7;
pipe20.diameter = 5.0;
pipe20.isInsulated = true;
pipe20.color = "Black";
System.out.println("Pipe 20: ");
System.out.println("Pipe ID: " + pipe20.pipeId);
System.out.println("Material: " + pipe20.material);
System.out.println("Length (meters): " + pipe20.length);
System.out.println("Diameter (inches): " + pipe20.diameter);
System.out.println("Is Insulated: " + pipe20.isInsulated);
System.out.println("Color: " + pipe20.color);
System.out.println();

}
}