class WeaponRunner {
    public static void main(String[] args) {

        Weapon weapon1 = new Weapon();
        weapon1.weaponId = 301;
        weapon1.type = "Sword";
        weapon1.material = "Steel";
        weapon1.weight = 3.5;
        weapon1.length = 90.0;
        weapon1.manufacturer = "BladeCo";
        weapon1.isAutomatic = false;
        System.out.println("Weapon 1: ");
        System.out.println("Weapon ID: " + weapon1.weaponId);
        System.out.println("Type: " + weapon1.type);
        System.out.println("Material: " + weapon1.material);
        System.out.println("Weight: " + weapon1.weight);
        System.out.println("Length: " + weapon1.length);
        System.out.println("Manufacturer: " + weapon1.manufacturer);
        System.out.println("Is Automatic: " + weapon1.isAutomatic);
        System.out.println();

        Weapon weapon2 = new Weapon();
        weapon2.weaponId = 302;
        weapon2.type = "Pistol";
        weapon2.material = "Aluminum";
        weapon2.weight = 1.2;
        weapon2.length = 25.0;
        weapon2.manufacturer = "GunMakers";
        weapon2.isAutomatic = true;
        System.out.println("Weapon 2: ");
        System.out.println("Weapon ID: " + weapon2.weaponId);
        System.out.println("Type: " + weapon2.type);
        System.out.println("Material: " + weapon2.material);
        System.out.println("Weight: " + weapon2.weight);
        System.out.println("Length: " + weapon2.length);
        System.out.println("Manufacturer: " + weapon2.manufacturer);
        System.out.println("Is Automatic: " + weapon2.isAutomatic);
        System.out.println();

        Weapon weapon3 = new Weapon();
        weapon3.weaponId = 303;
        weapon3.type = "Bow";
        weapon3.material = "Wood";
        weapon3.weight = 2.0;
        weapon3.length = 120.0;
        weapon3.manufacturer = "ArrowInc";
        weapon3.isAutomatic = false;
        System.out.println("Weapon 3: ");
        System.out.println("Weapon ID: " + weapon3.weaponId);
        System.out.println("Type: " + weapon3.type);
        System.out.println("Material: " + weapon3.material);
        System.out.println("Weight: " + weapon3.weight);
        System.out.println("Length: " + weapon3.length);
        System.out.println("Manufacturer: " + weapon3.manufacturer);
        System.out.println("Is Automatic: " + weapon3.isAutomatic);
        System.out.println();

        Weapon weapon4 = new Weapon();
        weapon4.weaponId = 304;
        weapon4.type = "Rifle";
        weapon4.material = "Steel";
        weapon4.weight = 4.5;
        weapon4.length = 100.0;
        weapon4.manufacturer = "GunMakers";
        weapon4.isAutomatic = true;
        System.out.println("Weapon 4: ");
        System.out.println("Weapon ID: " + weapon4.weaponId);
        System.out.println("Type: " + weapon4.type);
        System.out.println("Material: " + weapon4.material);
        System.out.println("Weight: " + weapon4.weight);
        System.out.println("Length: " + weapon4.length);
        System.out.println("Manufacturer: " + weapon4.manufacturer);
        System.out.println("Is Automatic: " + weapon4.isAutomatic);
        System.out.println();

        Weapon weapon5 = new Weapon();
        weapon5.weaponId = 305;
        weapon5.type = "Dagger";
        weapon5.material = "Steel";
        weapon5.weight = 0.5;
        weapon5.length = 30.0;
        weapon5.manufacturer = "BladeCo";
        weapon5.isAutomatic = false;
        System.out.println("Weapon 5: ");
        System.out.println("Weapon ID: " + weapon5.weaponId);
        System.out.println("Type: " + weapon5.type);
        System.out.println("Material: " + weapon5.material);
        System.out.println("Weight: " + weapon5.weight);
        System.out.println("Length: " + weapon5.length);
        System.out.println("Manufacturer: " + weapon5.manufacturer);
        System.out.println("Is Automatic: " + weapon5.isAutomatic);
        System.out.println();

        Weapon weapon6 = new Weapon();
        weapon6.weaponId = 306;
        weapon6.type = "Axe";
        weapon6.material = "Iron";
        weapon6.weight = 3.8;
        weapon6.length = 60.0;
        weapon6.manufacturer = "ForgeWorks";
        weapon6.isAutomatic = false;
        System.out.println("Weapon 6: ");
        System.out.println("Weapon ID: " + weapon6.weaponId);
        System.out.println("Type: " + weapon6.type);
        System.out.println("Material: " + weapon6.material);
        System.out.println("Weight: " + weapon6.weight);
        System.out.println("Length: " + weapon6.length);
        System.out.println("Manufacturer: " + weapon6.manufacturer);
        System.out.println("Is Automatic: " + weapon6.isAutomatic);
        System.out.println();

        Weapon weapon7 = new Weapon();
        weapon7.weaponId = 307;
        weapon7.type = "Crossbow";
        weapon7.material = "Wood and Steel";
        weapon7.weight = 4.2;
        weapon7.length = 95.0;
        weapon7.manufacturer = "ArrowInc";
        weapon7.isAutomatic = false;
        System.out.println("Weapon 7: ");
        System.out.println("Weapon ID: " + weapon7.weaponId);
        System.out.println("Type: " + weapon7.type);
        System.out.println("Material: " + weapon7.material);
        System.out.println("Weight: " + weapon7.weight);
        System.out.println("Length: " + weapon7.length);
        System.out.println("Manufacturer: " + weapon7.manufacturer);
        System.out.println("Is Automatic: " + weapon7.isAutomatic);
        System.out.println();

        Weapon weapon8 = new Weapon();
        weapon8.weaponId = 308;
        weapon8.type = "Mace";
        weapon8.material = "Iron";
        weapon8.weight = 2.7;
        weapon8.length = 50.0;
        weapon8.manufacturer = "ForgeWorks";
        weapon8.isAutomatic = false;
        System.out.println("Weapon 8: ");
        System.out.println("Weapon ID: " + weapon8.weaponId);
        System.out.println("Type: " + weapon8.type);
        System.out.println("Material: " + weapon8.material);
        System.out.println("Weight: " + weapon8.weight);
        System.out.println("Length: " + weapon8.length);
        System.out.println("Manufacturer: " + weapon8.manufacturer);
        System.out.println("Is Automatic: " + weapon8.isAutomatic);
        System.out.println();

        Weapon weapon9 = new Weapon();
        weapon9.weaponId = 309;
        weapon9.type = "Shotgun";
        weapon9.material = "Steel";
        weapon9.weight = 3.9;
        weapon9.length = 80.0;
        weapon9.manufacturer = "GunMakers";
        weapon9.isAutomatic = false;
        System.out.println("Weapon 9: ");
        System.out.println("Weapon ID: " + weapon9.weaponId);
        System.out.println("Type: " + weapon9.type);
        System.out.println("Material: " + weapon9.material);
        System.out.println("Weight: " + weapon9.weight);
        System.out.println("Length: " + weapon9.length);
        System.out.println("Manufacturer: " + weapon9.manufacturer);
        System.out.println("Is Automatic: " + weapon9.isAutomatic);
        System.out.println();

        Weapon weapon10 = new Weapon();
        weapon10.weaponId = 310;
        weapon10.type = "Halberd";
        weapon10.material = "Steel";
        weapon10.weight = 5.5;
        weapon10.length = 150.0;
        weapon10.manufacturer = "BladeCo";
        weapon10.isAutomatic = false;
        System.out.println("Weapon 10: ");
        System.out.println("Weapon ID: " + weapon10.weaponId);
        System.out.println("Type: " + weapon10.type);
        System.out.println("Material: " + weapon10.material);
        System.out.println("Weight: " + weapon10.weight);
        System.out.println("Length: " + weapon10.length);
        System.out.println("Manufacturer: " + weapon10.manufacturer);
        System.out.println("Is Automatic: " + weapon10.isAutomatic);
        System.out.println();

        Weapon weapon11 = new Weapon();
        weapon11.weaponId = 311;
        weapon11.type = "Katana";
        weapon11.material = "Steel";
        weapon11.weight = 1.5;
        weapon11.length = 70.0;
        weapon11.manufacturer = "Samurai Inc";
        weapon11.isAutomatic = false;
        System.out.println("Weapon 11: ");
        System.out.println("Weapon ID: " + weapon11.weaponId);
        System.out.println("Type: " + weapon11.type);
        System.out.println("Material: " + weapon11.material);
        System.out.println("Weight: " + weapon11.weight);
        System.out.println("Length: " + weapon11.length);
        System.out.println("Manufacturer: " + weapon11.manufacturer);
        System.out.println("Is Automatic: " + weapon11.isAutomatic);
        System.out.println();

        Weapon weapon12 = new Weapon();
        weapon12.weaponId = 312;
        weapon12.type = "Rapier";
        weapon12.material = "Steel";
        weapon12.weight = 1.0;
        weapon12.length = 90.0;
        weapon12.manufacturer = "BladeCo";
        weapon12.isAutomatic = false;
        System.out.println("Weapon 12: ");
        System.out.println("Weapon ID: " + weapon12.weaponId);
        System.out.println("Type: " + weapon12.type);
        System.out.println("Material: " + weapon12.material);
        System.out.println("Weight: " + weapon12.weight);
        System.out.println("Length: " + weapon12.length);
        System.out.println("Manufacturer: " + weapon12.manufacturer);
        System.out.println("Is Automatic: " + weapon12.isAutomatic);
        System.out.println();

        Weapon weapon13 = new Weapon();
        weapon13.weaponId = 313;
        weapon13.type = "Flail";
        weapon13.material = "Iron";
        weapon13.weight = 3.0;
        weapon13.length = 70.0;
        weapon13.manufacturer = "ForgeWorks";
        weapon13.isAutomatic = false;
        System.out.println("Weapon 13: ");
        System.out.println("Weapon ID: " + weapon13.weaponId);
        System.out.println("Type: " + weapon13.type);
        System.out.println("Material: " + weapon13.material);
        System.out.println("Weight: " + weapon13.weight);
        System.out.println("Length: " + weapon13.length);
        System.out.println("Manufacturer: " + weapon13.manufacturer);
        System.out.println("Is Automatic: " + weapon13.isAutomatic);
        System.out.println();

        Weapon weapon14 = new Weapon();
        weapon14.weaponId = 314;
        weapon14.type = "Musket";
        weapon14.material = "Wood and Steel";
        weapon14.weight = 5.0;
        weapon14.length = 110.0;
        weapon14.manufacturer = "GunMakers";
        weapon14.isAutomatic = false;
        System.out.println("Weapon 14: ");
        System.out.println("Weapon ID: " + weapon14.weaponId);
        System.out.println("Type: " + weapon14.type);
        System.out.println("Material: " + weapon14.material);
        System.out.println("Weight: " + weapon14.weight);
        System.out.println("Length: " + weapon14.length);
        System.out.println("Manufacturer: " + weapon14.manufacturer);
        System.out.println("Is Automatic: " + weapon14.isAutomatic);
        System.out.println();

        Weapon weapon15 = new Weapon();
        weapon15.weaponId = 315;
        weapon15.type = "Trident";
        weapon15.material = "Steel";
        weapon15.weight = 2.2;
        weapon15.length = 100.0;
        weapon15.manufacturer = "BladeCo";
        weapon15.isAutomatic = false;
        System.out.println("Weapon 15: ");
        System.out.println("Weapon ID: " + weapon15.weaponId);
        System.out.println("Type: " + weapon15.type);
        System.out.println("Material: " + weapon15.material);
        System.out.println("Weight: " + weapon15.weight);
        System.out.println("Length: " + weapon15.length);
        System.out.println("Manufacturer: " + weapon15.manufacturer);
        System.out.println("Is Automatic: " + weapon15.isAutomatic);
        System.out.println();

        Weapon weapon16 = new Weapon();
        weapon16.weaponId = 316;
        weapon16.type = "Throwing Knife";
        weapon16.material = "Steel";
        weapon16.weight = 0.3;
        weapon16.length = 20.0;
        weapon16.manufacturer = "BladeCo";
        weapon16.isAutomatic = false;
        System.out.println("Weapon 16: ");
        System.out.println("Weapon ID: " + weapon16.weaponId);
        System.out.println("Type: " + weapon16.type);
        System.out.println("Material: " + weapon16.material);
        System.out.println("Weight: " + weapon16.weight);
        System.out.println("Length: " + weapon16.length);
        System.out.println("Manufacturer: " + weapon16.manufacturer);
        System.out.println("Is Automatic: " + weapon16.isAutomatic);
        System.out.println();

        Weapon weapon17 = new Weapon();
        weapon17.weaponId = 317;
        weapon17.type = "Whip";
        weapon17.material = "Leather";
        weapon17.weight = 1.1;
        weapon17.length = 120.0;
        weapon17.manufacturer = "ForgeWorks";
        weapon17.isAutomatic = false;
        System.out.println("Weapon 17: ");
        System.out.println("Weapon ID: " + weapon17.weaponId);
        System.out.println("Type: " + weapon17.type);
        System.out.println("Material: " + weapon17.material);
        System.out.println("Weight: " + weapon17.weight);
        System.out.println("Length: " + weapon17.length);
        System.out.println("Manufacturer: " + weapon17.manufacturer);
        System.out.println("Is Automatic: " + weapon17.isAutomatic);
        System.out.println();

        Weapon weapon18 = new Weapon();
        weapon18.weaponId = 318;
        weapon18.type = "Halberd";
        weapon18.material = "Steel";
        weapon18.weight = 6.0;
        weapon18.length = 160.0;
        weapon18.manufacturer = "BladeCo";
        weapon18.isAutomatic = false;
        System.out.println("Weapon 18: ");
        System.out.println("Weapon ID: " + weapon18.weaponId);
        System.out.println("Type: " + weapon18.type);
        System.out.println("Material: " + weapon18.material);
        System.out.println("Weight: " + weapon18.weight);
        System.out.println("Length: " + weapon18.length);
        System.out.println("Manufacturer: " + weapon18.manufacturer);
        System.out.println("Is Automatic: " + weapon18.isAutomatic);
        System.out.println();

        Weapon weapon19 = new Weapon();
        weapon19.weaponId = 319;
        weapon19.type = "Spear";
        weapon19.material = "Wood and Steel";
        weapon19.weight = 3.0;
        weapon19.length = 140.0;
        weapon19.manufacturer = "BladeCo";
        weapon19.isAutomatic = false;
        System.out.println("Weapon 19: ");
        System.out.println("Weapon ID: " + weapon19.weaponId);
        System.out.println("Type: " + weapon19.type);
        System.out.println("Material: " + weapon19.material);
        System.out.println("Weight: " + weapon19.weight);
        System.out.println("Length: " + weapon19.length);
        System.out.println("Manufacturer: " + weapon19.manufacturer);
        System.out.println("Is Automatic: " + weapon19.isAutomatic);
        System.out.println();

        Weapon weapon20 = new Weapon();
        weapon20.weaponId = 320;
        weapon20.type = "Throwing Axe";
        weapon20.material = "Iron";
        weapon20.weight = 2.5;
        weapon20.length = 40.0;
        weapon20.manufacturer = "ForgeWorks";
        weapon20.isAutomatic = false;
        System.out.println("Weapon 20: ");
        System.out.println("Weapon ID: " + weapon20.weaponId);
        System.out.println("Type: " + weapon20.type);
        System.out.println("Material: " + weapon20.material);
        System.out.println("Weight: " + weapon20.weight);
        System.out.println("Length: " + weapon20.length);
        System.out.println("Manufacturer: " + weapon20.manufacturer);
        System.out.println("Is Automatic: " + weapon20.isAutomatic);
        System.out.println();

    }
}
